# tag 딕셔너리
tag_dict = {
    '1on1': ['1on1', '원온원'],
    'a/b test': ['a b testing', 'a/b test', 'ab test', 'ab 테스트', 'ab-testing', 'abtest', 'ab테스트'],
    'accessibility': ['accessibility', '접근성'],
    'ad tech': ['ad tech', 'adtech', 'advertising technology'],
    'agile': ['agile', '애자일'],
    'ai': ['ai', '인공지능'],
    'aiplus': ['aiplus', 'aiplus2020'],
    'ai스피커': ['ai 스피커', 'ai스피커'],
    'ai lab': ['ai lab', 'ai 연구소'],
    'ai research': ['ai research', 'ai서비스 ai연구', 'ai연구'],
    'ai학회' : ['ai학회', 'ai컨퍼런스'],
    'ai데이터': ['ai데이터', 'ai학습용데이터'],
    'algorithm': ['algorithm', 'algorithms', '알고리즘'],
    'andorid': ['andorid', 'android', '안드로이드'],
    'angular': ['angular', '앵귤러'],
    'angularjs': ['angular.js', 'angularjs'],
    'animation': ['animation', '애니메이션'],
    'anomaly-detection': ['anomaly-detection', '장애탐지'],
    'async': ['async', '비동기'],
    'automation': ['automation', '자동화'],
    'architecture': ['architecture', '아키텍처'],
    'aws': ['amazon web service', 'aws'],
    'api': ['api', 'api기술'],
    'app': ['app', '앱'],
    'app bundle': ['app bundle', '앱 번들'],
    'b+tree': ['b+tree', 'b+트리'],
    'babel': ['babel', 'babel7'],
    'backend': ['back-end', 'backend', '백엔드'],
    'back end developer': ['back end developer', 'backend developer'],
    'big data': ['big data', 'big-data', '빅데이터'],
    'blackhat': ['blackhat', '블랙햇'],
    'blind-recruitment': ['blind-recruitment', '2022_blind', '2023_blind'],
    'blockchain': ['block chain', 'blockchain', '블록체인'],
    'blog': ['blog', '블로그'],
    'bluetooth': ['bluetooth', '블루투스'],
    'branding': ['branding', '브랜딩'],
    'branching strategy': ['branching strategy', '브랜치 전략'],
    'business': ['business', '비즈니스'],
    'cache': ['cache', '캐시'],
    'chatbot': ['cahtbot', 'catbot', '챗봇'],
    'career': ['career', 'careers'],
    'cgroup': ['cgroup', 'cgroups'],
    'certification': ['certification','인증'],
    'cloud': ['cloud', '클라우드'],
    'cloud/infra': ['clout/infra', 'cloud/infra'],
    'code quality': ['code quality', '코드품질'],
    'code review': ['code review', 'code-review', 'codereview', '코드 리뷰', '코드리뷰'],
    'code-festival': ['code-festival', 'codefest'],
    'coding test': ['coding test', 'coing test', '코딩 테스트'],
    'collaborative filtering': ['collaborative filtering', 'cf'],
    'ci' : ['ci', 'continuous integration', 'continuous-integration'],
    'cd' : ['cd', 'continuous-delivery'],
    'cnn' : ['cnn', 'convolutional neural network(cnn)'],
    'collection': ['collection', '컬렉션'],
    'cookie': ['cookie', '쿠키'],
    'company culture': ['company culture', '사내문화'],
    'connection-pool': ['connection-pool', '커넥션풀'],
    'covid-19': ['covid-19', '코로나'],
    'cross functional teams': ['cross functional teams', 'crossfunctional teams'],
    'cross platform': ['cross platform', '크로스플랫폼'],
    'css': ['css', 'css3'],
    'cubrid': ['cubrid', '큐브리드'],
    'culture': ['culture', '문화'],
    'd2campus': ['d2campus', 'd2campu'],
    'data': ['data', '데이터','@data'],
    'data analytics': ['data analytic', 'data analytics', '데이터분석'],
    'data engineering': ['data engineering', '데이터엔지니어링'],
    'data foundation': ['data foundation', '데이터파운데이션', '데이터구축'],
    'elasticsearch': ['elasticsearch', '엘라스틱서치'],
    'emoji': ['emoji', '이모지'],
    'engineering': ['engineering', '엔지니어링'],
    'entity tagging': ['entity tagging', '엔티티 태깅'],
    'event': ['event', '이벤트'],
    'experiment': ['experiment', 'experimentation', '실험'],
    'experiment platform': ['experiment platform', '실험플랫폼'],
    'facebook': ['facebook', '페이스북'],
    'fastapi': ['fast api', 'fastapi'],
    'front end': ['front-end', 'frontend', '프론트엔드'],
    'frontend development': ['front end development', 'frontend development'],
    'functional-programming': ['functional-programming', '함수형 프로그래밍', '함수형프로그래밍'],
    'game day': ['gameday', 'gameday'],
    'garbage-collection': ['garbage-collection', 'garbagecollection', 'gc', '가비지컬렉션'],
    'get-server': ['get-server', 'get-server-10'],
    'github': ['github', '깃허브'],
    'github actions': ['github action', 'github actions', 'github-actions'],
    'google': ['google', '구글'],
    'google analytics':['google analytics', '구글애널리틱스'],
    'googleio': ['googleio', 'google io 2019'],
    'go': ['go', 'go언어'],
    'graphdb': ['graphdb', '그래프데이터베이스'],
    'growth': ['growth', '성장'],
    'hash': ['hash', '해시'],
    'helloworld': ['helloworld', 'heloworld'],
    'heykakao': ['heykakao', '헤이카카오'],
    'html': ['html', 'html5'],
    'iclr': ['iclr', 'iclr 2020', 'iclr2020'],
    'if kakao': ['if kakao', 'ifkakao', 'ifkakao-2022', 'ifkakao2022'],
    'index': ['index', '인덱스'],
    'infra': ['infra', 'infrastructure', '인프라'],
    'internship': ['internship', '인턴십'],
    'javascript': ['javascript', '자바스크립트'],
    'jira': ['jira', '지라'],
    'junior': ['junior', 'junior developer', '신입개발자'],
    'jdk': ['jdk7', 'jdk8'],
    'kafka connect': ['kafka connect', 'kafka-connect'],
    'kakao': ['kakao', '카카오'],
    'kakao enterprise': ['kakao enterprise', '카카오엔터프라이즈'],
    'kakao i': ['kakao i', '카카오i'],
    'kakao i cloud': ['kakao i cloud', '카카오 i 클라우드'],
    'kakaocommerce': ['kakao-commerce', 'kakaocommerce'],
    'keras': ['keras', '케라스'],
    'kubernetes': ['kubernetes', 'k8s', '쿠버네티스'],
    'lambda': ['lambda', '람다'],
    'legacy': ['legacy', '레거시'],
    'license': ['license', '라이선스'],
    'line': ['line', '라인'],
    'line games': ['line game', 'line games'],
    'line developer day': ['line developer day', 'linedevday'],
    'livestreaming': ['livestreaming', '라이브스트림'],
    'log': ['log', '로그'],
    'machine learning': ['machine learning', 'machine-learning', 'ml', '머신러닝'],
    'manager': ['manager', 'manger', '매니저'],
    'marketing': ['marketing', '마케팅'],
    'map': ['map', 'maps', '지도'],
    'media-server': ['media-server', '미디어서버'],
    'memoization': ['memoization', '메모이제이션'],
    'memory': ['memory', '메모리'],
    'memory-leak': ['memory-leak', '메모리 누수'],
    'metric': ['metric', 'metrics'],
    'metric learning': ['metric learning', '메트릭러닝'],
    'microservice': ['microservice', 'microservices', '마이크로서비스'],
    'mini link': ['mini link', '미니링크'],
    'mobile': ['mobile', '모바일'],
    'monorepo': ['monorepo', '모노레포'],
    'monitoring': ['monitoring', '모니터링'],
    'musinsa': ['musinsa', '무신사'],
    'musinsatech': ['musinsatech', '무신사테크'],
    'mydata': ['mydata', '마이데이터'],
    'naver search': ['naver search', '네이버 검색', '네이버검색'],
    'native app': ['native app', '네이티브앱'],
    'network': ['network', '네트워크'],
    '신규입사자': ['new-krew', 'new-krew-2023', '2021-new-krew', '신규입사자'],
    'next.js': ['next.js', 'nextjs'],
    'nlp': ['natural language process', 'nlp', '자연어처리'],
    'node.js': ['nodejs', 'node.js'],
    'notification': ['notification', '공지'],
    'neural machine translation': ['neural machine translation', '인공신경망 기반 기계 번역', '인공신경망 기계번역'],
    'oauth': ['oauth', 'oauth 2.1', 'oauth2'],
    'observability': ['observability', '옵저버빌리티'],
    'onboarding': ['onboarding', '온보딩'],
    'open api': ['open api', 'openapi', '오픈api'],
    'open source': ['open source', 'opensource', '오픈소스'],
    'openflow': ['openflow', '오픈플로'],
    'organizational culture': ['organizational culture', '조직문화'],
    'performance': ['performance', '성능'],
    'performance tuning': ['performance tuning', '성능개선'],
    'persona': ['persona', '페르소나'],
    'planning': ['planning', '계획', '기획'],
    'planningshop': ['planningshop', '플래닝샵'],
    'platform': ['platform', '플랫폽'],
    'pm' : ['pm', 'project manager'],
    'power user curve': ['power user curve', '파워유저커브'],
    'product': ['product', '프로덕트'],
    'product owner': ['product owner', 'product-owner'],
    'product design': ['product design', 'productdesign', '프로덕트디자인'],
    'product designer': ['product designer', 'productdesigner'],
    'product language': ['product language', '프로덕트랭귀지'],
    'product-owner': ['product-owner', 'productowner'],
    'programming': ['programming', 'programing', '프로그래밍'],
    'programming-contest': ['programming-contest', '공개sw개발자대회'],
    'push': ['push', '푸시'],
    'pycon': ['pycon.kr', 'pycon', 'pycon2019'],
    'python': ['python', '파이썬'],
    're:invent': ['re:invent', 're:invent2022'],
    'react': ['react', '리액트'],
    'react native': ['react native', 'react-native'],
    'react query': ['react query', 'react-query', '리액트 쿼리'],
    'react': ['react', 'react18'],
    'reactive-programming': ['reactive-programming', '반응형 프로그래밍'],
    'rebranding': ['rebranding', '리브랜딩'],
    'recommendation': ['recommendation', '추천'],
    'recommendation system': ['recommendation system', 'recommendation-system','recommender-system', '추천시스템'],
    'recruit': ['recruit', 'recruitment', 'recruitmenttech', '개발자 채용', '개발자채용', '채용'],
    'rendering': ['rendering', '렌더링'],
    'retrospective': ['retrospective', 'retrospectives', '회고'],
    'scroll': ['scroll', '스크롤'],
    'search': ['search', 'serch', '검색'],
    'security': ['security', '보안'],
    'server': ['server', 'servers', '서버'],
    'service': ['service', 'services'],
    'session': ['session', '세션'],
    'spoofing': ['spoofing', '스푸핑'],
    'slack': ['slack', '슬랙'],
    'slackbot': ['slackbot', '슬랙봇'],
    'slot filling': ['slot filling', '슬롯 필링'],
    'slot tagging': ['slot tagging', '슬롯 태깅'],
    'social-login': ['social-login', '소셜로그인'],
    'spark': ['spark', '스파크'],
    'spring batch': ['spring batch', 'springbatch'],
    'spring boot': ['spring boot', 'springboot'],
    'startup': ['startup', '스타트업'],
    'storage': ['storage', '스토리지', '저장소'],
    'streaming': ['streaming', '스트리밍'],
    'survey': ['survey', 'serveys'],
    'tech blog': ['tech blog', 'techblog', '기술블로그'],
    'tech': ['tech', 'technology'],
    'technical writing': ['technical writing', '테크니컬 라이팅'],
    'tech spec': ['tech spec', '테크스펙'],
    'test': ['test', '테스트'],
    'testing': ['testing', '테스팅'],
    'thread': ['thread', '스레드'],
    'timeseries': ['timeseries', '시계열'],
    'transformer': ['transfomer', 'transformer'],
    'transaction': ['transaction', '트랜잭션'],
    'traffic': ['traffic', '트래픽'],
    'typescript': ['typescript', '타입스크립트'],
    'unit test': ['unit test', 'unit-test', 'unittest'],
    'untact': ['untact', '비대면', 'remote working'],
    'usa': ['usa', '미국'],
    'usabilitytest': ['usabilitytest', '사용성테스트', '사용성평가'],
    'ux design': ['ux design', '유엑스디자인'],
    'viewpager': ['viewpager', 'viewpager2'],
    'vue.js': ['vue', 'vue.js'],
    'watcha': ['watcha', '왓챠'],
    'web': ['web', '웹', 'web3'],
    'webapp': ['webapp', '웹앱'],
    'webbrowser': ['webbrowser', '웹브라우저', '브라우저'],
    'webfont': ['webfont', '웹폰트'],
    'web-performance': ['web-performance', '웹성능'],
    'webview': ['webview', '웹뷰'],
    'web-worker':  ['web-worker', 'webworkers'],
    'workflow automation': ['workflow automation', '업무자동화'],
    'workshop': ['workshop', '워크샵'],
    'yogiyo': ['yogiyo', '요기요'],
    'zum': ['zum', 'zum.com'],
    '개인화 추천': ['개인화 추천', '개인화추천'],
    '대화 엔진': ['대화 엔진', '대화엔진'],
    '딥러닝': ['딥러닝', '딥려닝'],
    '디자인': ['디자인', '디자인 '],
    '동영상 플랫폼': ['동영상 플랫폼', '동영상플랫폼'],
    '데이터 플랫폼': ['데이터 플랫폼', '데이터플랫폼'],
    '스몰톡봇': ['스몰톡봇', '스몰톡챗봇'],
    '외개인아가': ['외개인', '외개인아가'],
    '음성인식기술': ['음성인식처리', '음성인식기술', '음성인식처리기술'],
    '카카오 i 번역': ['카카오 i 번역', '카카오i번역'],
    '음성인식스피커': ['음성인식스피커', '인공지능스피커'],
    '음성생성': ['음성생성', '음성합성'],
    '일하는방법': ['일하는방법', '일하는방식'],
    '호출 명령어': ['호출 명령어', '호출명령어'],
    '핵심어 검출': ['핵심어 검출', '핵심어검출']
}


# 달을 숫자로 변환 하는 딕셔너리들
month_dict1 = {
    "Jan": "01",
    "Feb": "02",
    "Mar": "03",
    "Apr": "04",
    "May": "05",
    "Jun": "06",
    "Jul": "07",
    "Aug": "08",
    "Sep": "09",
    "Oct": "10",
    "Nov": "11",
    "Dec": "12"
    } 
month_dict2 = {
    "January": "01",
    "February": "02",
    "March": "03",
    "April": "04",
    "May": "05",
    "June": "06",
    "July": "07",
    "August": "08",
    "September": "09",
    "October": "10",
    "November": "11",
    "December": "12"
}