# Generated by Django 4.2.7 on 2023-11-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="url",
            field=models.URLField(max_length=300, verbose_name="링크"),
        ),
    ]
