# Generated by Django 4.2.7 on 2023-11-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("techs", "0002_alter_post_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="url", field=models.TextField(verbose_name="링크"),
        ),
    ]
